name: piano_analytics_plugin_example
description: Demonstrates how to use the piano_analytics_plugin plugin.
version: 0.0.5
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  piano_analytics_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true